### ISSUE TITLE
"building-database" repo name

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-app#116]
…is "building-database" the most accurate name for this anymore? Is it mostly front-end at this point or could it still be stood up as a unique instance of the whole app?

**Comment by robhawkes** [comment]
This was chosen in a bit of a rush and without much thought – I definitely vote that this should be renamed to something more appropriate.

The repo is effectively the entire application, front- and back-end. Arguably, most of the interesting stuff happens back-end, not that it should have an effect on the name.

We could just go for polygon-city, or perhaps polygon-city-app. Or something else?

**Comment by meetar** [comment]
Sure, either of those works for me – @bcamper ?

**Comment by bcamper** [comment]
Same :)

**Comment by bcamper** [comment]
I suppose `polygon-city-app` might be most accurate, though slightly wordier.

**Comment by robhawkes** [comment]
Out of the two I prefers `polygon-city-app`, mainly because it's more correct and avoids potential confusion with the org name.

I don't know if changing the repo name still causes issues for anyone who uses this repo as a remote (eg. us, the dev server, etc) and requires manually updating. I know it used to be the case but I'm pretty sure I changed a repo not long ago and GitHub automatically redirected the old requests.

Anyone have recent experience with this?

**Comment by bcamper** [comment]
Oh yes I've renamed many a repo, sometimes multiple times :)  It redirects everything (though you should still update your remote). The only issues we've seen are with `gh-pages`, I believe (sometimes they work, sometimes they don't? I we've had caching issues there).

**Comment by robhawkes** [comment]
That's good to know. Well changing the name here isn't complicated – we can do that immediately so long as it's not going to screw up the dev server. Shall I go ahead and change it to `polygon-city-app`?

**Comment by bcamper** [comment]
Go ahead - @baldur we should update on the server side when we get a chance too, but i don't believe this should break anything since github redirects.

**Comment by robhawkes** [comment]
All changed! I'll close this under the assumption that we'll update the necessary remotes.
